ALTER TABLE products ADD COLUMN IF NOT EXISTS code TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS model TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS supplier TEXT DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit_measure TEXT DEFAULT 'UNIDAD';
ALTER TABLE products ADD COLUMN IF NOT EXISTS tax DECIMAL(5,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS surcharge DECIMAL(5,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS bulk_price DECIMAL(12,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS item_type TEXT DEFAULT 'producto' CHECK (item_type IN ('producto', 'servicio'));
ALTER TABLE products ADD COLUMN IF NOT EXISTS check_list TEXT DEFAULT 'NO';
ALTER TABLE products ADD COLUMN IF NOT EXISTS labor_cost DECIMAL(12,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS net_price DECIMAL(12,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS alicuota DECIMAL(5,2) DEFAULT 0;

CREATE TABLE IF NOT EXISTS services (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  code TEXT DEFAULT '',
  name TEXT NOT NULL,
  category TEXT DEFAULT 'general',
  check_list TEXT DEFAULT 'NO',
  labor_cost DECIMAL(12,2) DEFAULT 0,
  net_price DECIMAL(12,2) DEFAULT 0,
  surcharge DECIMAL(5,2) DEFAULT 0,
  alicuota DECIMAL(5,2) DEFAULT 0,
  bulk_price DECIMAL(12,2) DEFAULT 0,
  description TEXT DEFAULT '',
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage own services" ON services FOR ALL USING (user_id = auth.uid());